# Generated by Django 5.1.2 on 2024-10-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FF', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
