# Generated by Django 5.1.2 on 2024-10-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FF', '0004_addresss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signups',
        ),
    ]
