# Generated by Django 3.2.7 on 2024-10-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FF', '0005_delete_signups'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresss',
            name='Country',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresss',
            name='Shipping',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
