# Generated by Django 5.1.2 on 2024-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FF', '0007_auto_20241022_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='pin',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
